web:
  image: ngdly/nginx-add-concat
  volumes:
    - ./wwwroot:/usr/share/nginx/html
    - ./nginx/conf.d:/etc/nginx/conf.d
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=domain1.com
    - NGINX_PORT=80